fig = uifigure;
message = ['This session contains ', 13, ' trials, however only ', 10, ...
    ' are fully video-mointored (according to your current reference frame). Select CANCEL to quit the analysis ', ...
    ' or Analyse anyways instead. Be extremly careful with the latter option. Make sure, that the missing trials ', ...
    ' are at the end and NOT at the beginning of the session, otherwise you just get noise.'];
selection = uiconfirm(fig,message,'Confirm choice','Options',{'Cancel', 'Analyse anyways'}, 'Defaultoption', 1, ...
'Canceloption',1,'Icon','Warning');
close(fig)
selection